# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: "3.7"

services:
  db:
    restart: unless-stopped
    image: postgres:13
    command: postgres
    environment:
      POSTGRES_DB: "touchstone-api"
      POSTGRES_USER: "touchstone-api"
      POSTGRES_PASSWORD: "touchstone-api_dev"
    ports:
      - "5432:5432"
