name: Deploy

on: push

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl apps create-deployment 6763dc0d-a440-404d-9c3e-54aef099789f
