name: Deploy

on:
  release:
    branches:
      - master

jobs:
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
