name: Testing

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker-compose up -d db
      - run: echo "Checking syntax"
      - run: gofmt -e **/*.go > /dev/null
      - run: echo "Testing"
      - run: make test
